version: "3"

services:
  sonarqube:
    image: sonarqube:8.9.0-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks: 
      - sonarnet
    environment: 
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    # volumes:
    #   - sonarqube_data:/opt/sonarqube/data
    #   - sonarqube_extensions:/opt/sonarqube/extensions
    #   - sonarqube_logs:/opt/sonarqube/logs
    #   - sonarqube_temp:/opt/sonarqube/temp

networks:
  sonarnet:
    driver: bridge

# volumes:
#   sonarqube_data:
#   sonarqube_extensions:
#   sonarqube_logs:
#   sonarqube_temp: