version: '2'
services:
  servico-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
    container_name: jhipster-registry
  servico-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.8
    container_name: elastic
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports:
      - 9200:9200
    mem_limit: 1512M
    networks:
      - registry-net
  servico-ldap:
    image: osixia/openldap:1.3.0
    container_name: openldap
    environment:
      - "LDAP_ORGANISATION=EB MIL"
      - "LDAP_DOMAIN=eb.mil.br"
      - "LDAP_ADMIN_PASSWORD=admin"
    ports:
      - 8389:389
      - 636:636
  redis:
    extends:
      file: redis.yml
      service: redis
    container_name: redis

networks:
  registry-net:
