version: '2'
services:
  lab-mssql:
    container_name: lab-mysql
    extends:
      file: mssql.yml
      service: lab-mssql
    mem_limit: 1024M
    volumes:
    - mssql_data:/var/opt/mssql/data/

volumes:
  mssql_data: