version: '3.7'

services:
  teste-postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
    ports:
      - "15432:5432"
    volumes:
      - ./volume/database/postgresql:/var/lib/postgresql/data 
    networks:
      - postgres-network
      
  teste-pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "wedson.silva@basis.com.br"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "16543:80"
    depends_on:
      - teste-postgres
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge