version: '3.7'

services:
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"
    networks:
      - redis-network
networks: 
  redis-network:
    driver: bridge